puts "1xBanana!"
puts "2xBanana!"
puts "4xBanana!"
puts "5xBanana!"
puts "7xBanana!"
puts "8xBanana!"
puts "10xBanana!"
puts "11xBanana!"
puts "12xBanana!"
puts "13xBanana!"
puts "9xBanana!"
puts "18xBanana!"
puts "19xBanana!"
puts "14xBanana!"
puts "14xBanana!"
puts "15xBanana!"
puts "16xBanana!"
puts "17xBanana!"
puts "All minions are cool!"
puts "All minions are ugly!"
puts "All minions are hired!"
puts "21xBanana!"